export { default as Game } from './Game'
export { default as Agent } from './Agent'
export { default as Settings } from './Settings'
export { default as If } from './If'
export { default as TabTemplate } from './TabTemplate'
